### ISSUE TITLE
"Animate controls and elements inside windows"

### ISSUE THREAD

**Issue by Regnander** [Wallpaper-Engine-Team/wallpaper-engine-translations#193]
Wallpaper Engine will enable "Animate controls and elements inside windows" in "Performance Options" even if you try to disable the option while it's running.

My OS is Windows 8.1.

**Comment by TiEul** [comment]
Sorry, but this is not an issue tracker or support board for Wallpaper Engine. Check the Steam Community discussions.

**Comment by Regnander** [comment]
Alright, I'll create a post there right away!
