### ISSUE TITLE
core_nn-no.json and ui_nn-no.json named wrong

### ISSUE THREAD

**Issue by alberten** [Wallpaper-Engine-Team/wallpaper-engine-translations#343]
Shouldn't core_nn-no.json and ui_nn-no.json be named core_nb-no.json and ui_nb-no.json?

In Norway, we have two writing systems nb-no Norwegian Bokmål and nn-no Norwegian Nynorsk. 
Norwegian Bokmål is the most used. If I go into the files then I see that the writing system that is used is Norwegian Bokmål.
Therefore the files should be named core_nb-no.json and ui_nb-no.json.

**Comment by TiEul** [comment]
Hey, thanks for the info, we definitely did not know about this difference. I will fix this some time when I get around it (also requires some changes to the app itself so that has to be synced), thanks!
