### ISSUE TITLE
[Question] Crowdin support

### ISSUE THREAD

**Issue by tehLuaX** [Wallpaper-Engine-Team/wallpaper-engine-translations#376]
This is a question regarding pull request #372: I was wondering if the Wallpaper Engine translation project will be shifted towards Crowdin or if it's just giving people that want to contribute another way of translating Wallpaper Engine.

**Comment by TiEul** [comment]
Hey, I am still looking into it but yes, I think in the future the community translations will move to a platform like Crowdin. It just makes it easier to keep track of changes and to do the actual translations. We will also be able to hire professional translators much more easily which was a bit of a hassle in the past.

**Comment by tehLuaX** [comment]
Okay, thanks for the response!
