### ISSUE TITLE
Crowdin proofreaders

### ISSUE THREAD

**Issue by Regnander** [Wallpaper-Engine-Team/wallpaper-engine-translations#420]
Can we who previously worked on the translation here on Github (and are still interested in contributing) become proofreaders on Crowdin for our respective language?

My nickname on Crowdin is [FirePhoenix](https://crowdin.com/profile/FirePhoenix)

**Comment by TiEul** [comment]
Hey, does "translator" not give you the same rights as proof-reader? I thought it contains the same set of features. Is there something you cannot access?

**Comment by Regnander** [comment]
If two translation suggestions have the same amount of votes, the newer one will take priority and get pushed to production.

A proofreader has the ability to mark these suggestions as "approved", which overrides this priority and makes it impossible to vandalize the project if no other translators have voted on the serious suggestion.

Of course, if a serious translator comes in and suggests a valid improvement on an already approved translation, they can create and mark a comment as an issue to notify the proofread of the language.

**Comment by Regnander** [comment]
Just to illustrate, here is a mockup on what I mean could happen on some languages which doesn't have any active voters:

![aaaa](https://user-images.githubusercontent.com/17113053/91486207-389c2e80-e8ac-11ea-8417-b4be1e6a301f.png)

**Comment by comradekingu** [comment]
Set a license for the project, and use Weblate. Otherwise the only party able to use the strings is Crowdin, as it sublicenses strings into its closed translation memory.
Will contribute if I see the project on Hosted Weblate. :)

**Comment by TiEul** [comment]
@Regnander Thanks for clearing that up. I have set your role as "proofreader" for Swedish now. I think it's best to keep this on a per-case basis as we have paid translators for some languages now and we handle those languages differently compared to "community-only" languages like Swedish.
